version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: jobint_user
      POSTGRES_PASSWORD: Karen_2003
      POSTGRES_DB: jobint
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:                       # ← проверяем, что Postgres принимает соединения
      test: ["CMD-SHELL", "pg_isready -U jobint_user"]
      interval: 5s
      timeout: 3s
      retries: 12

  auth_service:
    build: .
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:                        # ← ждём, пока healthcheck станет 'healthy'
      db:
        condition: service_healthy

volumes:
  pgdata:
