version: "3.9"

services:
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file: .env
    command: python -m app.main
    restart: unless-stopped
    volumes:
      - ./jobint.sqlite3:/srv/jobint.sqlite3
      - ./anon.session:/srv/anon.session  # если нужен файл сессии Telethon

# Для SQLite отдельный сервис базы не нужен!
