version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: jobint_user
      POSTGRES_PASSWORD: Karen_2003
      POSTGRES_DB: jobint
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U jobint_user"]
      interval: 5s
      timeout: 3s
      retries: 12
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  auth_service:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8001"

volumes:
  pgdata:
