version: "3.9"

services:
  auth_service:
    build: .
    env_file:
      - .env
    ports:
      - "8001:8001"
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: jobint_user
      POSTGRES_PASSWORD: Karen_2003
      POSTGRES_DB: jobint
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: