version: "3.9"

services:
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file: .env
    command: hypercorn app.main:app --bind 0.0.0.0:8001
    restart: unless-stopped
    volumes:
      - ./app:/app/app
      - ./jobint.sqlite3:/app/jobint.sqlite3
