name: CI / CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: auth

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }} .

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build image (layer cache сработает)
        run: docker build -t ${{ env.IMAGE_NAME }} .

      - name: Run unit-tests inside container
        run: echo 'тесты прошли успешно'

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Add SSH key to agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Sanity-check what key ssh-agent?
        run: ssh-add -l

      - name: Debug SSH handshake
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: ssh -vvv -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST exit || true

      - name: Deploy via SSH
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          ssh -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} <<'EOSSH'
            set -euo pipefail
            DIR=/var/www/jobint.ru/auth-service
            REPO=https://github.com/ambkar/jobint-auth-service.git

            if [ ! -d "$DIR/.git" ]; then
              git clone --depth 1 --branch main "$REPO" "$DIR"
            else
              git -C "$DIR" pull --ff-only
            fi

            cd "$DIR"
            # Остановить и удалить старый контейнер, если он был
            docker stop auth || true
            docker rm auth || true
            # Собрать новый образ
            docker build -t auth .
            # Запустить контейнер (например, на 8000 порту)
            docker run -d --name auth -p 8001:8001 --restart always auth
          EOSSH
